export const Data = [
  {
    name: "single economy",
    slug: "single-economy",
    type: "single",
    price: 100,
    size: 200,
    capacity: 1,
    pets: false,
    breakfast: false,
    featured: false,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level",
  },
  {
    name: "single basic",
    slug: "single-basic",
    type: "single",
    price: 150,
    size: 250,
    capacity: 1,
    pets: false,
    breakfast: false,
    featured: false,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray",
  },
  {
    name: "single standard",
    slug: "single-standard",
    type: "single",
    price: 250,
    size: 300,
    capacity: 1,
    pets: true,
    breakfast: false,
    featured: false,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tof",
  },
  {
    name: "single deluxe",
    slug: "single-deluxe",
    type: "single",
    price: 300,
    size: 400,
    capacity: 1,
    pets: true,
    breakfast: true,
    featured: false,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level",
  },
  {
    name: "double economy",
    slug: "double-economy",
    type: "double",
    price: 200,
    size: 300,
    capacity: 4,
    pets: false,
    breakfast: false,
    featured: false,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level,",
  },
  {
    name: "double basic",
    slug: "double-basic",
    type: "double",
    price: 250,
    size: 350,
    capacity: 4,
    pets: false,
    breakfast: false,
    featured: false,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct",
  },
  {
    name: "double standard",
    slug: "double-standard",
    type: "double",
    price: 300,
    size: 400,
    capacity: 2,
    pets: true,
    breakfast: false,
    featured: false,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level,",
  },
  {
    name: "double deluxe",
    slug: "double-deluxe",
    type: "double",
    price: 400,
    size: 500,
    capacity: 2,
    pets: true,
    breakfast: true,
    featured: true,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray",
  },
  {
    name: "family economy",
    slug: "family-economy",
    type: "family",
    price: 300,
    size: 500,
    capacity: 3,
    pets: false,
    breakfast: false,
    featured: false,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wo",
  },
  {
    name: "family basic",
    slug: "family-basic",
    type: "family",
    price: 350,
    size: 550,
    capacity: 4,
    pets: false,
    breakfast: false,
    featured: false,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha port",
  },
  {
    name: "family standard",
    slug: "family-standard",
    type: "family",
    price: 400,
    size: 600,
    capacity: 5,
    pets: true,
    breakfast: false,
    featured: false,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, d",
  },
  {
    name: "family deluxe",
    slug: "family-deluxe",
    type: "family",
    price: 500,
    size: 700,
    capacity: 6,
    pets: true,
    breakfast: true,
    featured: true,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled c",
  },
  {
    name: "presidential",
    slug: "presidential-room",
    type: "presidential",
    price: 600,
    size: 1000,
    capacity: 10,
    pets: true,
    breakfast: true,
    featured: true,
    description:
      "Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humble",
  },
];
